# Generated by Django 6.0 on 2026-01-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=120)),
                ('telephone', models.BigIntegerField()),
                ('dateinvitation', models.DateTimeField()),
                ('commune', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=120)),
                ('invitepar', models.CharField(max_length=150)),
                ('motifdepresence', models.CharField(max_length=200)),
                ('communauteorigine', models.CharField(max_length=200)),
            ],
        ),
    ]
