# Generated by Django 6.0 on 2026-01-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appguestlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invites',
            name='Activitepro',
            field=models.CharField(default='Non renseigné', max_length=100),
        ),
        migrations.AddField(
            model_name='invites',
            name='groupesanguin',
            field=models.CharField(default='O+', max_length=3),
        ),
        migrations.AddField(
            model_name='invites',
            name='ministere',
            field=models.CharField(default='ND', max_length=100),
        ),
        migrations.AddField(
            model_name='invites',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='invites/photos/'),
        ),
        migrations.AddField(
            model_name='invites',
            name='sitmatrimoniale',
            field=models.CharField(default='Célibataire', max_length=40),
            preserve_default=False,
        ),
    ]
