# Generated by Django 6.0 on 2026-01-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appguestlist', '0002_invites_activitepro_invites_groupesanguin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='Activitepro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invites',
            name='groupesanguin',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='invites',
            name='ministere',
            field=models.CharField(max_length=100),
        ),
    ]
