# Generated by Django 6.0 on 2026-01-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appguestlist', '0003_alter_invites_activitepro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='invites/photos'),
        ),
        migrations.AlterField(
            model_name='invites',
            name='telephone',
            field=models.CharField(),
        ),
    ]
